stages:
  - build
  - deploy

.setup_docker: &setup_docker_engine
  before_script:
    - git clean -d --dry-run
    - echo $CI_ENVIRONMENT_NAME
    - chmod +x env_build.sh
    - bash env_build.sh
  script:
    - echo "setup docker succeed"

.rool_back: &rool_back_action
  script:
    - docker system prune -af 
    - docker volume prune -f
    - docker compose up -d --build
    - echo "Migration Started"
    - docker compose exec web python manage.py migrate
    - echo "========== Migration Done ============"
    - echo "Deployed to $CI_ENVIRONMENT_NAME"

deploy_dev:
  <<: *setup_docker_engine
  <<: *rool_back_action
  stage: deploy
  environment:
    name: dev
    url: https://demo.example.com
  only:
    - dev
  tags:
    - dev-backend